services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: https://example.com
    command: server /data --console-address ":9090"
    networks:
      - intranet

networks:
  intranet:
    external: true
