services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
    networks:
      - intranet

networks:
  intranet:
    external: true
